USE [master]
GO

/****** Object:  Database [SelectDormitory]    Script Date: 2024/9/24 16:54:54 ******/
CREATE DATABASE [SelectDormitory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SelectDormitory', FILENAME = N'E:\SQL server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SelectDormitory.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SelectDormitory_log', FILENAME = N'E:\SQL server\MSSQL16.MSSQLSERVER\MSSQL\DATA\SelectDormitory_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SelectDormitory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SelectDormitory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SelectDormitory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SelectDormitory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SelectDormitory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SelectDormitory] SET ARITHABORT OFF 
GO

ALTER DATABASE [SelectDormitory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SelectDormitory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SelectDormitory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SelectDormitory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SelectDormitory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SelectDormitory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SelectDormitory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SelectDormitory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SelectDormitory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SelectDormitory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SelectDormitory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SelectDormitory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SelectDormitory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SelectDormitory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SelectDormitory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SelectDormitory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SelectDormitory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SelectDormitory] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SelectDormitory] SET  MULTI_USER 
GO

ALTER DATABASE [SelectDormitory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SelectDormitory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SelectDormitory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SelectDormitory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SelectDormitory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SelectDormitory] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SelectDormitory] SET QUERY_STORE = ON
GO

ALTER DATABASE [SelectDormitory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SelectDormitory] SET  READ_WRITE 
GO

